arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_link__link1
    - link1__link2
    - link2__link3
    - link3__link4
    - link4__link5
    - gripper_joint
  gains:
    base_link__link1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link1__link2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link2__link3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link3__link4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link4__link5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_left_joint
    - gripper_right_joint
  gains:
    gripper_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1